#!/usr/bin/env tsx
/**
 * Could `Event.tags` back a topic-tag FACET, the way a category facet is backed today?
 *
 * The question came out of auditing events.heapheaphurray.com, which attaches a keyword to
 * 100% of its events — `Agents` on 6 of 20, `GenAI` on 5, plus Go-to-Market, Founders,
 * No-Code, MLOps, SaaS — a finer layer than our 22 coarse categories. The obvious response is
 * "expose the tags we already collect". This measures whether we actually collect any.
 *
 * Measured 2026-08-24: we do not. Of 1212 upcoming events, 32 carry any tag at all and only
 * **8 of 334** tech events do. There are SIX distinct tag values in the entire corpus, and the
 * most common was `district` — a source marker one of our own adapters was appending, since
 * removed. Meetup, our largest source at 881 upcoming events, supplies exactly 1.
 *
 * So the conclusion is the opposite of the easy one: a tag facet cannot be built on harvested
 * tags, because the supply is not there. Tags would have to be GENERATED by the tagger, which
 * is a much larger piece of work than surfacing an existing field — and it competes for the
 * same LLM budget as the categories that already work. Re-run this before anyone plans a tag
 * feature on the assumption that the data exists.
 *
 * `tags` is still doing a real job: it is passed to the tagger as `hints`. It is just not a
 * facet source.
 *
 * Read-only.
 *
 * Run: npx tsx scripts/diag-tag-supply.ts
 */
import './load-env';
import connectDB from '../lib/mongodb';
import Event from '../lib/models/Event';
import mongoose from 'mongoose';

async function main() {
  await connectDB();
  const now = new Date();
  const upcoming = { startDateTime: { $gte: now } };
  const total = await Event.countDocuments(upcoming);
  const tech = await Event.countDocuments({ ...upcoming, isTechEvent: true });
  const withTags = await Event.countDocuments({ ...upcoming, tags: { $ne: [] } });
  const techWithTags = await Event.countDocuments({ ...upcoming, isTechEvent: true, tags: { $ne: [] } });
  console.log('upcoming=' + total + ' tech=' + tech + ' withTags=' + withTags + ' techWithTags=' + techWithTags);

  const bySource = await Event.aggregate([
    { $match: upcoming },
    {
      $group: {
        _id: '$source',
        n: { $sum: 1 },
        tagged: { $sum: { $cond: [{ $gt: [{ $size: { $ifNull: ['$tags', []] } }, 0] }, 1, 0] } },
      },
    },
    { $sort: { n: -1 } },
  ]);
  console.log('\nby source (upcoming):');
  for (const r of bySource) {
    console.log('  ' + String(r._id).padEnd(16) + ' n=' + String(r.n).padStart(4) + ' tagged=' + String(r.tagged).padStart(4));
  }

  const distinct = await Event.aggregate([
    { $match: { ...upcoming, tags: { $ne: [] } } },
    { $unwind: '$tags' },
    { $group: { _id: '$tags' } },
    { $count: 'c' },
  ]);
  const topTags = await Event.aggregate([
    { $match: { ...upcoming, tags: { $ne: [] } } },
    { $unwind: '$tags' },
    { $group: { _id: '$tags', count: { $sum: 1 }, srcs: { $addToSet: '$source' } } },
    { $sort: { count: -1 } },
    { $limit: 60 },
  ]);
  console.log('\ndistinct tag values (top 60 of ' + (distinct[0]?.c ?? 0) + '):');
  for (const t of topTags) {
    console.log('  ' + String(t.count).padStart(4) + '  ' + t._id + '   [' + t.srcs.join(',') + ']');
  }

  const techTags = await Event.aggregate([
    { $match: { ...upcoming, isTechEvent: true, tags: { $ne: [] } } },
    { $unwind: '$tags' },
    { $group: { _id: '$tags', count: { $sum: 1 }, srcs: { $addToSet: '$source' } } },
    { $sort: { count: -1 } },
    { $limit: 40 },
  ]);
  console.log('\nTAGS IN THE DEFAULT (techOnly) FEED - what a facet would actually render:');
  for (const t of techTags) {
    console.log('  ' + String(t.count).padStart(4) + '  ' + t._id + '   [' + t.srcs.join(',') + ']');
  }

  await mongoose.disconnect();
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
